### ISSUE TITLE
Endpoint for Username Alias History

### ISSUE THREAD

**Issue by SwiftCODA** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#80]
I notice on Tracker Network that they show past usernames associated with each profile id. Do you know of any endpoints where I could retrieve that information?

**Comment by Seems2Legit** [comment]
As far as I'm aware no endpoint provides past usernames. You need to collect/cache user-profiles and save his old username once it has been changed. This although requires (to work precisely) many requests in order to catch name changes from a large userbase. 

I'd suggest that you use a third-party API like e.g. 
https://developers.statsdb.net/

It's not open-source/selfhosted but I'm not aware of a better alternative.

**Comment by SwiftCODA** [comment]
I'm using their API for a leaderboard at the moment. Thanks anyways.
